import React, { useEffect, useRef } from 'react';
import {
  Badge,
  Button,
} from '@fluentui/react-components';
import {
  ArrowDownloadRegular,
  DeleteDismissRegular,
  SparkleRegular,
  DataHistogramRegular,
  ChartMultipleRegular,
  DataPieRegular,
  ArrowSwapRegular,
  PrintRegular,
} from '@fluentui/react-icons';
import { useSessionStore } from '../../store/useSessionStore';
import { usePluginStore } from '../../store/usePluginStore';
import { SessionItem } from './SessionItem';
import { printSessionReport } from '../../utils/projectIo';

export const SessionPane: React.FC = () => {
  const { items, activeItemId, clearSession, exportSessionText } = useSessionStore();
  const { openDialog } = usePluginStore();
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // Auto scroll when activeItemId changes
  useEffect(() => {
    if (activeItemId) {
      const el = document.getElementById(`session-${activeItemId}`);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }
    }
  }, [activeItemId, items.length]);

  const handleDownloadOutput = () => {
    const text = exportSessionText();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `libretab_session_${new Date().toISOString().slice(0, 10)}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full flex flex-col bg-[#f8f9fa] border-b border-[#d8dce0] overflow-hidden select-none session-pane-root">
      {/* Pane Header */}
      <div className="flex items-center justify-between px-3 py-1.5 bg-[#eaeef2] border-b border-[#d8dce0] text-xs font-semibold text-[#323130] session-pane-header">
        <div className="flex items-center gap-2">
          <DataHistogramRegular className="text-[#008450]" />
          <span>Session Output Pane</span>
          {items.length > 0 && (
            <Badge size="small" appearance="filled" color="brand">
              {items.length}
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-1.5">
          {items.length > 0 && (
            <>
              <Button
                appearance="subtle"
                size="small"
                icon={<PrintRegular />}
                onClick={printSessionReport}
                title="Print or Save Session Results as PDF Report (Ctrl+P)"
                className="font-medium text-indigo-700"
              >
                Print Report (PDF)
              </Button>
              <Button
                appearance="subtle"
                size="small"
                icon={<ArrowDownloadRegular />}
                onClick={handleDownloadOutput}
                title="Export complete session transcript (.txt)"
              >
                Export Log
              </Button>
              <Button
                appearance="subtle"
                size="small"
                icon={<DeleteDismissRegular />}
                onClick={clearSession}
                title="Clear all analysis outputs"
              >
                Clear Output
              </Button>
            </>
          )}
        </div>
      </div>


      {/* Pane Content */}
      <div
        ref={scrollContainerRef}
        className="flex-1 overflow-y-auto p-4 space-y-4"
      >
        {/* Official Report Header (Visible in Print / PDF Export) */}
        <div className="hidden print:block mb-6 pb-3 border-b-2 border-[#008450]">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-xl font-bold text-[#111827] tracking-tight">LibRE Tab — Statistical Analysis Report</h1>
              <p className="text-xs text-[#4b5563] mt-0.5">
                Session history • {items.length} analysis {items.length === 1 ? 'module' : 'modules'}
              </p>
            </div>
            <div className="text-right text-xs text-[#4b5563]">
              <p className="font-semibold text-[#111827]">Date: {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })}</p>
              <p>Generated by LibRE Tab Statistical Workbench</p>
            </div>
          </div>
        </div>

        {items.length === 0 ? (

          <div className="h-full min-h-[160px] flex flex-col items-center justify-center text-center p-6 border-2 border-dashed border-[#d2d0ce] rounded-xl bg-white/70 shadow-xs">
            <div className="w-12 h-12 rounded-full bg-[#ebf3fc] text-[#008450] flex items-center justify-center mb-3 shadow-inner">
              <SparkleRegular className="w-6 h-6" />
            </div>
            <h4 className="text-sm font-semibold text-[#201f1e] mb-1">
              Ready for Statistical Analysis
            </h4>
            <p className="text-xs text-[#605e5c] max-w-md mb-4 leading-relaxed">
              Select a statistical tool from the top <strong>Stat</strong> menu or launch one of the quick analysis workflows below.
            </p>
            <div className="flex flex-wrap gap-2 justify-center">
              <Button
                appearance="primary"
                icon={<DataHistogramRegular />}
                onClick={() => openDialog('display_descriptives')}
              >
                Descriptive Statistics
              </Button>
              <Button
                appearance="secondary"
                icon={<ChartMultipleRegular />}
                onClick={() => openDialog('two_sample_t')}
              >
                2-Sample t-Test
              </Button>
              <Button
                appearance="secondary"
                icon={<DataPieRegular />}
                onClick={() => openDialog('one_way_anova')}
              >
                One-Way ANOVA
              </Button>
              <Button
                appearance="secondary"
                icon={<ArrowSwapRegular />}
                onClick={() => openDialog('correlation')}
              >
                Correlation Matrix
              </Button>
            </div>
          </div>
        ) : (
          items.map((item) => (
            <SessionItem key={item.id} item={item} isActive={item.id === activeItemId} />
          ))
        )}
      </div>
    </div>
  );
};
